- name: 開発ツールのインストール
  become: yes
  yum: name='@Development Tools'

- name: RubyとPassengerのビルドに必要な開発ツールやヘッダファイルのインストール
  become: yes
  yum:
    name='openssl-devel,readline-devel,zlib-devel,curl-devel,libyaml-devel,libffi-devel'

- name:  PostgreSQLとヘッダファイルのインストール
  become: yes
  yum:
    name='postgresql-server,postgresql-devel,python-psycopg2'

- name: Apacheとヘッダファイルのインストール
  become: yes
  yum:
    name='httpd,httpd-devel'

- name: ImageMagickとヘッダファイル・日本語フォントのインストール
  become: yes
  yum:
    name='ImageMagick,ImageMagick-devel,ipa-pgothic-fonts'

- name: そのほかのツールのインストール
  become: yes
  yum:
    name='subversion,git,which'

- name: 作業ディレクトリ作成
  file: path={{ work_dir }}
    state=directory
    mode=0755
